### ISSUE TITLE
有个小问题,鼠标拖动窗口的时候有点不跟手

### ISSUE THREAD

**Issue by akl7777777** [duolabmeng6/qoq#2]
有个小问题,鼠标拖动窗口的时候有点不跟手,总是鼠标移动了很远,窗口移动一半就不动了

**Comment by akl7777777** [comment]
慢速拖动没问题,很快拖动会有这个问题

**Comment by duolabmeng6** [comment]
收到收到~~这个问题我也想解决 不过我不会...是不太跟手

**Comment by duolabmeng6** [comment]
这个我还真解决不了..除非顶部的工具条用qt原生的组件... 如果不是很影响的话 我也不是很想处理这个问题....qt上以浏览器开发ui的资料很少..我几乎搜不到资料...可以体验一下最新的版本 会自适应显示内容了 也不太需要调整位置

**Comment by duolabmeng6** [comment]
已修复 等新版本发布 接口 很丝滑~~~
