### ISSUE TITLE
以后可以添加deepl官方api和deeplX翻译吗

### ISSUE THREAD

**Issue by yeenjie123456** [duolabmeng6/qoq#3]

**Comment by duolabmeng6** [comment]
会的 由于我没有 deep的账户 所以还没有增加
qoq后面会尝试加入自定义执行脚本 例如本应用的翻译接口 都在这里开源
https://github.com/duolabmeng6/pyefun/tree/master/pyefun/%E7%BF%BB%E8%AF%91

**Comment by duolabmeng6** [comment]
我尝试兼容一下 bob的插件吧 看起来是可以的样子....

**Comment by duolabmeng6** [comment]
已加入 deepl 的 免秘钥版本https://github.com/akl7777777/bob-plugin-akl-deepl-free-translate
后续我研究一下以插件形式加入
